import { Footer, Navbar } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Abril_Fatface, Inter, Roboto } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const abril = Abril_Fatface({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-abril",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} ${abril.variable} font-sans`}
      >
        <div className="absolute top-0 left-0 w-full h-full flex justify-evenly -z-10 pointer-events-none">
          {/* line 1 */}
          {[0, 1, 2, 3].map((item) => (
            <div className="bg-tertiary w-[1px] min-h-full relative"></div>
          ))}
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
